version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
  league_app:
    build: .
    volumes:
      - .:/workspace
    ports:
      - 8000:8000
    image: league_app:latest
    container_name: league_app_container
    command: python league_bot/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  pgadmin:
      container_name: pgadmin4_league
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
volumes:
  db: