# Generated by Django 4.0.3 on 2022-04-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0004_remove_match_id_match_duration_match_game_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='start_time',
            field=models.BigIntegerField(null=True),
        ),
    ]
