# Generated by Django 4.0.3 on 2022-06-08 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0010_remove_participant_puuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_id',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='match_id',
            new_name='match',
        ),
    ]
