# Generated by Django 4.0.3 on 2022-06-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0012_championstats_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('champ_name', models.CharField(default='Default name', max_length=50, primary_key=True, serialize=False)),
                ('champ_play_count', models.IntegerField(default=-1, null=True)),
                ('champ_winrate', models.FloatField(default=-1, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ChampionStats',
        ),
    ]
