# Generated by Django 4.0.3 on 2022-07-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0013_champion_delete_championstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item0', models.IntegerField(default=1, null=True)),
                ('item1', models.IntegerField(default=1, null=True)),
                ('item2', models.IntegerField(default=1, null=True)),
                ('item3', models.IntegerField(default=1, null=True)),
                ('item4', models.IntegerField(default=1, null=True)),
                ('item5', models.IntegerField(default=1, null=True)),
                ('win_rate', models.FloatField(default=1, null=True)),
            ],
        ),
    ]
