# Generated by Django 4.0.3 on 2022-07-21 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0014_builds'),
    ]

    operations = [
        migrations.AddField(
            model_name='builds',
            name='champ_name',
            field=models.ForeignKey(default='Default name', on_delete=django.db.models.deletion.CASCADE, to='league_bot.champion'),
        ),
    ]
