# Generated by Django 4.0.3 on 2022-07-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0016_remove_builds_id_builds_build_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builds',
            name='item1',
        ),
        migrations.RemoveField(
            model_name='builds',
            name='item2',
        ),
        migrations.RemoveField(
            model_name='builds',
            name='item3',
        ),
        migrations.RemoveField(
            model_name='builds',
            name='item4',
        ),
        migrations.RemoveField(
            model_name='builds',
            name='item5',
        ),
    ]
