# Generated by Django 4.0.3 on 2022-07-22 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0017_remove_builds_item1_remove_builds_item2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Builds',
            new_name='Slot_0_Items',
        ),
        migrations.CreateModel(
            name='Slot_5_Items',
            fields=[
                ('build_id', models.CharField(default=0, max_length=50, primary_key=True, serialize=False)),
                ('item5', models.IntegerField(default=1, null=True)),
                ('win_rate', models.FloatField(default=1, null=True)),
                ('champ_name', models.ForeignKey(default='Default name', on_delete=django.db.models.deletion.CASCADE, to='league_bot.champion')),
            ],
        ),
        migrations.CreateModel(
            name='Slot_4_Items',
            fields=[
                ('build_id', models.CharField(default=0, max_length=50, primary_key=True, serialize=False)),
                ('item4', models.IntegerField(default=1, null=True)),
                ('win_rate', models.FloatField(default=1, null=True)),
                ('champ_name', models.ForeignKey(default='Default name', on_delete=django.db.models.deletion.CASCADE, to='league_bot.champion')),
            ],
        ),
        migrations.CreateModel(
            name='Slot_3_Items',
            fields=[
                ('build_id', models.CharField(default=0, max_length=50, primary_key=True, serialize=False)),
                ('item3', models.IntegerField(default=1, null=True)),
                ('win_rate', models.FloatField(default=1, null=True)),
                ('champ_name', models.ForeignKey(default='Default name', on_delete=django.db.models.deletion.CASCADE, to='league_bot.champion')),
            ],
        ),
        migrations.CreateModel(
            name='Slot_2_Items',
            fields=[
                ('build_id', models.CharField(default=0, max_length=50, primary_key=True, serialize=False)),
                ('item2', models.IntegerField(default=1, null=True)),
                ('win_rate', models.FloatField(default=1, null=True)),
                ('champ_name', models.ForeignKey(default='Default name', on_delete=django.db.models.deletion.CASCADE, to='league_bot.champion')),
            ],
        ),
        migrations.CreateModel(
            name='Slot_1_Items',
            fields=[
                ('build_id', models.CharField(default=0, max_length=50, primary_key=True, serialize=False)),
                ('item1', models.IntegerField(default=1, null=True)),
                ('win_rate', models.FloatField(default=1, null=True)),
                ('champ_name', models.ForeignKey(default='Default name', on_delete=django.db.models.deletion.CASCADE, to='league_bot.champion')),
            ],
        ),
    ]
