# Generated by Django 4.0.3 on 2022-07-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0018_rename_builds_slot_0_items_slot_5_items_slot_4_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot_0_items',
            name='play_count',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='slot_1_items',
            name='play_count',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='slot_2_items',
            name='play_count',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='slot_3_items',
            name='play_count',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='slot_4_items',
            name='play_count',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AddField(
            model_name='slot_5_items',
            name='play_count',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='slot_0_items',
            name='item0',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='slot_0_items',
            name='win_rate',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='slot_1_items',
            name='item1',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='slot_1_items',
            name='win_rate',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='slot_2_items',
            name='item2',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='slot_2_items',
            name='win_rate',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='slot_3_items',
            name='item3',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='slot_3_items',
            name='win_rate',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='slot_4_items',
            name='item4',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='slot_4_items',
            name='win_rate',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='slot_5_items',
            name='item5',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='slot_5_items',
            name='win_rate',
            field=models.FloatField(default=-1, null=True),
        ),
    ]
