# Generated by Django 4.0.3 on 2022-07-24 07:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0019_slot_0_items_play_count_slot_1_items_play_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot_0_items',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=[], size=10),
        ),
    ]
