# Generated by Django 4.0.3 on 2022-07-24 07:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0020_slot_0_items_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot_1_items',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=[], size=10),
        ),
        migrations.AddField(
            model_name='slot_2_items',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=[], size=10),
        ),
        migrations.AddField(
            model_name='slot_3_items',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=[], size=10),
        ),
        migrations.AddField(
            model_name='slot_4_items',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=[], size=10),
        ),
        migrations.AddField(
            model_name='slot_5_items',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=[], size=10),
        ),
    ]
