# Generated by Django 4.0.3 on 2022-07-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0021_slot_1_items_tags_slot_2_items_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot_0_items',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='slot_1_items',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='slot_2_items',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='slot_3_items',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='slot_4_items',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='slot_5_items',
            name='tags',
        ),
    ]
