# Generated by Django 4.0.3 on 2022-07-24 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0022_remove_slot_0_items_tags_remove_slot_1_items_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion_Items',
            fields=[
                ('info_key', models.CharField(default='default000', max_length=50, primary_key=True, serialize=False)),
                ('item_id', models.IntegerField(null=True)),
                ('play_count', models.IntegerField(null=True)),
                ('champ_name', models.ForeignKey(default='Default name', on_delete=django.db.models.deletion.CASCADE, to='league_bot.champion')),
            ],
        ),
        migrations.RemoveField(
            model_name='slot_1_items',
            name='champ_name',
        ),
        migrations.RemoveField(
            model_name='slot_2_items',
            name='champ_name',
        ),
        migrations.RemoveField(
            model_name='slot_3_items',
            name='champ_name',
        ),
        migrations.RemoveField(
            model_name='slot_4_items',
            name='champ_name',
        ),
        migrations.RemoveField(
            model_name='slot_5_items',
            name='champ_name',
        ),
        migrations.DeleteModel(
            name='Slot_0_Items',
        ),
        migrations.DeleteModel(
            name='Slot_1_Items',
        ),
        migrations.DeleteModel(
            name='Slot_2_Items',
        ),
        migrations.DeleteModel(
            name='Slot_3_Items',
        ),
        migrations.DeleteModel(
            name='Slot_4_Items',
        ),
        migrations.DeleteModel(
            name='Slot_5_Items',
        ),
    ]
