# Generated by Django 4.0.3 on 2022-07-24 23:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0023_champion_items_remove_slot_1_items_champ_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(default='default', max_length=50)),
                ('gold', models.IntegerField(null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=10)),
            ],
        ),
    ]
