# Generated by Django 4.0.3 on 2022-07-27 04:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0024_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='builds_into',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=10),
        ),
        migrations.AlterField(
            model_name='champion_items',
            name='item_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='league_bot.items'),
        ),
        migrations.AlterField(
            model_name='items',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=10),
        ),
    ]
