# Generated by Django 4.0.3 on 2022-07-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0025_items_builds_into_alter_champion_items_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_name',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
