# Generated by Django 4.0.3 on 2022-07-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0026_alter_items_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='plain_text',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
