# Generated by Django 4.0.3 on 2022-07-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0027_items_plain_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='plain_text',
            new_name='description',
        ),
    ]
