# Generated by Django 4.0.3 on 2022-08-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0028_rename_plain_text_items_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runes',
            fields=[
                ('rune_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rune_name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
