# Generated by Django 4.0.3 on 2022-08-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0029_runes'),
    ]

    operations = [
        migrations.AddField(
            model_name='runes',
            name='rune_cat',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
