# Generated by Django 4.0.3 on 2022-08-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0030_runes_rune_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='runes',
            name='rune_icon',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
