# Generated by Django 4.0.3 on 2022-04-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0005_alter_match_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='part_puuid',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
