# Generated by Django 4.0.3 on 2022-04-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0007_alter_participant_part_puuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='puuid',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
