# Generated by Django 4.0.3 on 2022-05-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0009_participant_perks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='puuid',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='summoner_id',
        ),
        migrations.AddField(
            model_name='match',
            name='insertion_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='insertion_date',
            field=models.DateTimeField(null=True),
        ),
    ]
