# Generated by Django 4.0.3 on 2022-06-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_bot', '0011_rename_match_id_match_match_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionStats',
            fields=[
                ('champ_name', models.CharField(default='Default name', max_length=50, primary_key=True, serialize=False)),
                ('champ_play_count', models.IntegerField(null=True)),
                ('champ_winrate', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
